# Generated by Django 5.0 on 2025-03-19 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'работник',
                'verbose_name_plural': 'работники',
            },
        ),
        migrations.CreateModel(
            name='PPEItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название СИЗ')),
                ('default_replacement_days', models.IntegerField(default=7, verbose_name='Срок замены (дни)')),
            ],
            options={
                'verbose_name': 'Средство индивидуальной защиты',
                'verbose_name_plural': 'Средства индивидуальной защиты',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название территории')),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территории',
            },
        ),
        migrations.CreateModel(
            name='IssuedPPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата последней замены')),
                ('replacement_date', models.DateField(editable=False, verbose_name='Следующая дата замены')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Группы.employee', verbose_name='Работник (ФИО)')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Группы.ppeitem', verbose_name='СИЗ')),
            ],
            options={
                'verbose_name': 'Выданные СИЗ',
                'verbose_name_plural': 'Выданные СИЗ',
            },
        ),
        migrations.CreateModel(
            name='StaffLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, null=True, unique=True, verbose_name='Номер лаборатории')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название лаборатории')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Группы.region', verbose_name='Территория')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Группы.stafflaboratory', verbose_name='Лаборатория'),
        ),
    ]
