# Generated by Django 5.0 on 2025-03-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название периода')),
                ('months', models.IntegerField(verbose_name='Количество месяцев')),
            ],
            options={
                'verbose_name': 'Период замены',
                'verbose_name_plural': 'Периоды замены',
            },
        ),
        migrations.RemoveField(
            model_name='ppeitem',
            name='default_replacement_days',
        ),
        migrations.AddField(
            model_name='ppeitem',
            name='replacement_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Группы.replacementperiod', verbose_name='Период замены'),
        ),
    ]
