# Generated by Django 5.0 on 2025-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0002_replacementperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacementperiod',
            name='months',
            field=models.IntegerField(null=True, verbose_name='Количество месяцев'),
        ),
    ]
