# Generated by Django 5.0 on 2025-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0003_alter_replacementperiod_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppeitem',
            name='replacement_period',
        ),
        migrations.AddField(
            model_name='ppeitem',
            name='replacement_period_type',
            field=models.CharField(choices=[('days', 'Дни'), ('months', 'Месяцы'), ('years', 'Годы')], default='months', max_length=10, verbose_name='Тип периода замены'),
        ),
        migrations.AddField(
            model_name='ppeitem',
            name='replacement_period_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Период замены'),
        ),
        migrations.DeleteModel(
            name='ReplacementPeriod',
        ),
    ]
