# Generated by Django 5.0 on 2025-03-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0005_alter_stafflaboratory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflaboratory',
            name='number',
        ),
    ]
