# Generated by Django 5.0 on 2025-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0006_remove_stafflaboratory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflaboratory',
            name='number',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Номер лаборатории'),
        ),
    ]
