# Generated by Django 5.0 on 2025-03-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0007_stafflaboratory_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafflaboratory',
            options={'verbose_name': 'Лаборатория', 'verbose_name_plural': 'Лаборатории'},
        ),
        migrations.AlterField(
            model_name='stafflaboratory',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Номер лаборатории'),
        ),
    ]
