# Generated by Django 5.0 on 2025-03-25 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0011_stafflaboratory_universal_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflaboratory',
            name='universal_admin',
        ),
        migrations.AlterField(
            model_name='stafflaboratory',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_lab', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
