# Generated by Django 5.0 on 2025-03-25 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0012_remove_stafflaboratory_universal_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflaboratory',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_labs', to=settings.AUTH_USER_MODEL, verbose_name='для Работники'),
        ),
        migrations.AlterField(
            model_name='stafflaboratory',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_labs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
