# Generated by Django 5.0 on 2025-03-26 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0013_stafflaboratory_admin_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflaboratory',
            name='universal_admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_all_labs', to=settings.AUTH_USER_MODEL, verbose_name='главный админ'),
        ),
    ]
