# Generated by Django 5.0 on 2025-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0014_stafflaboratory_universal_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflaboratory',
            name='universal_admin',
        ),
    ]
