# Generated by Django 5.0 on 2025-04-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Группы', '0015_remove_stafflaboratory_universal_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppeitem',
            options={'verbose_name': 'Средств индивидуальной защиты и проверка знаний', 'verbose_name_plural': 'Средств индивидуальной защиты и проверка знаний'},
        ),
    ]
